### PR TITLE
Update build.yml

### PR DESCRIPTION
**Pull request by ABirHAsan123-beep**
[Build and test](https://github.com/AndroidIDEOfficial/AndroidIDE/actions/workflows/build.yml)

### CODE REVIEW

**Comment by ABirHAsan123-beep** [comment]
https://github.com/AndroidIDEOfficial/AndroidIDE/pull/1838/commits/e3ac4f67fb3c751782695feacb8aa5ccd1e66bae

**Comment by BanDroid** [comment]
dont playing with the repo issue and PR!

**Review by ABirHAsan123-beep — COMMENTED** [review]
e3ac4f67fb3c751782695feacb8aa5ccd1e66bae

**Comment by ABirHAsan123-beep** [comment]
> dont playing with the repo issue and PR!

**Pull request closed without merging**
